CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    price DECIMAL(19,2) NOT NULL,
    quantity DECIMAL(19,2) NOT NULL,
    type VARCHAR(50) NOT NULL,
    value DECIMAL(19,2) NOT NULL,
    user_id BIGINT,
    wallet_id BIGINT,
    stock_id BIGINT,
    active BOOLEAN NOT NULL DEFAULT true
);

INSERT INTO orders (id, price, quantity, type, value, user_id, wallet_id, stock_id, active) VALUES
(1, 100.50, 10.00, 'BUY', 1005.00, 1, 2, 3, true),
(2, 95.75, 25.50, 'SELL', 2441.63, 2, 3, 1, true),
(3, 150.00, 5.00, 'BUY', 750.00, 3, 1, 2, true),
(4, 200.25, 8.75, 'SELL', 1752.19, 1, 2, 3, false),
(5, 75.80, 100.00, 'BUY', 7580.00, 2, 3, 1, true),
(6, 300.00, 2.50, 'SELL', 750.00, 3, 1, 2, true),
(7, 45.30, 50.00, 'BUY', 2265.00, 1, 2, 3, true),
(8, 180.90, 15.25, 'SELL', 2758.73, 2, 3, 1, false),
(9, 120.00, 20.00, 'BUY', 2400.00, 3, 1, 2, true),
(10, 85.45, 30.75, 'SELL', 2627.59, 1, 2, 3, true),
(11, 250.75, 4.00, 'BUY', 1003.00, 2, 3, 1, true),
(12, 90.20, 12.50, 'SELL', 1127.50, 3, 1, 2, true),
(13, 175.00, 6.80, 'BUY', 1190.00, 1, 2, 3, false),
(14, 110.30, 22.00, 'SELL', 2426.60, 2, 3, 1, true),
(15, 65.75, 40.00, 'BUY', 2630.00, 3, 1, 2, true);